name: Thử nghiệm đọc file README
on:
  push:
    branches: ["main"] # Code mới đẩy lên main

jobs:
  thuc_hanh_doc_file:
    runs-on: ubuntu-latest #Mượn máy ảo github

    steps:
      - name: Bước 1 - Xin chào
        run: echo "Hello World"  #Lệnh in ra màn hình 

      - name: Bước 2 - Tải code (Checkout)
        uses: actions/checkout@v6.0.2 #Robot tự động

      - name: Bước 3 - Đọc file
        run: cat README.md 
